### ISSUE TITLE
建議

### ISSUE THREAD

**Issue by Kiruilo** [lulu2002/Naluwan-Issues#10]
希望可以讓會員可以辦活動 插件的(EVENTS) 就是那種pvp一般伺服器會有的events 然後舉辦就可以進去 裡面是1v1淘汰賽

**Comment by lulu2002** [comment]
感謝建議，那魯灣之後會有另類的活動系統，敬請期待！

**Comment by lulu2002** [comment]
同時您已經開過建議囉，如果一個討論串尚未結束，請您不要隨意按下 「Close Issue」的按鈕，謝謝！
