### ISSUE TITLE
希望有個可以通知其他玩家對戰的系統

### ISSUE THREAD

**Issue by YukiSnowYue** [lulu2002/Naluwan-Issues#103]
如標題
 除了前面幾個模式常常可以排到人以外
很多比較冷門的模式都沒辦法有機會排到
如果想玩 除了邀請朋友外就只能乾等了
雖然可以透過GUI的數字看有沒有人在排
但希望能用主動通知的方式 來減低等待的時間

**Comment by lulu2002** [comment]
依照以往的經驗，不管是小遊戲，還是任何公告，都只會在一開始有用，到後期玩家麻痺後其實有跟沒有差不多，這是為什麼我不想新增公告的原因，因為作用不大。

依然開放討論空間，如果沒有進一步資訊，我會再關掉這版
