### ISSUE TITLE
沙漠A地圖漏洞回報

### ISSUE THREAD

**Issue by ruby6625** [lulu2002/Naluwan-Issues#108]
![2021-10-24_21 32 07](https://user-images.githubusercontent.com/52475539/138597226-ef84c6b5-6801-41d0-8c98-17bfcfc22362.png)
這張地圖樹上沒有放屏障 希望可以在上面新增以防止玩家skybase

**Comment by lulu2002** [comment]
地圖各有優缺點，實在很難依照每張圖做改進，還是謝謝你提供意見！
