### ISSUE TITLE
伺服器/msg訊息阻擋

### ISSUE THREAD

**Issue by NEHL714** [lulu2002/Naluwan-Issues#111]
在伺服器遊玩遭人挑釁
China HK
SUCKER Hk
要求伺服器正視
該垃圾ID
Sou5
本人留有法律權利追數

**Comment by lulu2002** [comment]
那魯灣的訊息皆不是在公頻發布的，已超出伺服器職責範圍。
關於法律訴訟部份，可以找第三方審查單位處理，那魯灣不會干涉。
