### ISSUE TITLE
我想要把帳號解除dc綁定

### ISSUE THREAD

**Issue by Pudding7tw** [lulu2002/Naluwan-Issues#120]
因為我換了一個dc帳號 所以我想解除綁定 謝謝 
minecraft帳號名:Pudding7_tw
原dc帳號:盜版布丁寧
現dc帳號:布丁寧

**Comment by lulu2002** [comment]
請回報 工作人員，這裡是用來回報伺服器 bug 的喔。

**Comment by Pudding7tw** [comment]
好的 謝謝
