### ISSUE TITLE
提問有關那魯灣discord的問題

### ISSUE THREAD

**Issue by power930806** [lulu2002/Naluwan-Issues#36]
魯魯你好我想請問那魯灣discord有一個玩家社群招生的頻道,可是沒有辦法發送訊息,這個頻道有打算對玩家開放嗎,我想宣傳我的discord群組,不知道有沒有辦法

**Comment by lulu2002** [comment]
該頻道原本有打算開放，後來因為某些因素而取消該計畫了，所以目前暫時不會有社群招生的功能喔。
