### ISSUE TITLE
建議 - IGN系統新增功能選項

### ISSUE THREAD

**Issue by Tealeaf01** [lulu2002/Naluwan-Issues#37]
現在在那魯灣IGN玩家，會同時：
1. 在配對模式遇不到對方
2.看不到對方在公頻打的字
3.對方無法私訊自己

我認為「1.」和「2.、3.」可以分成兩個類別，因為IGN一位玩家，原因可能只是不想跟對方打，或者只是不想看到他打的字；

例如做法可以是：把IGN指令改成
a.「/ign pvp [<對方ID>]」
b.「/ign chat [<對方ID>]」
c.「/ign all [<對方ID>]」

指令a.只是做功能1.，指令b.只是做功能2.和3.，指令c.就同時做到功能1.、2.、3.

這樣就可以更精準地IGN別人

如有說得不清楚的地方，而你又想了解清楚，可以DC找：ChaYe#6534
謝謝

**Comment by lulu2002** [comment]
感謝建議！那魯灣其實最近剛好在更新 ign 功能，這個提議內容極佳，之後會加入遊戲中！

**Comment by lulu2002** [comment]
![image](https://user-images.githubusercontent.com/41278925/122662764-220eed00-d1c8-11eb-954e-76d708e05b92.png)
![image](https://user-images.githubusercontent.com/41278925/122662767-2804ce00-d1c8-11eb-9da0-27258a829b87.png)

完成囉！下次那魯灣更新這功能便會套用上去
