### ISSUE TITLE
[bug回報]擊退回朔

### ISSUE THREAD

**Issue by FBIJustGotMe** [lulu2002/Naluwan-Issues#38]
魯魯你好 :
我和朋友自訂了一個模式 
可以將對方擊退很遠的距離 在不久前還可以用 
但今天玩這個模式的時候 只要被擊退太遠都會被傳送回地圖正中央 
希望可以修正 
辛苦了

**Comment by lulu2002** [comment]
感謝回報！

**Comment by lulu2002** [comment]
已修正，更新後即會套用
