### ISSUE TITLE
Cave fight, Hypixel head, HitMLG BUGS

### ISSUE THREAD

**Issue by Zayaix** [lulu2002/Naluwan-Issues#42]
在Cave fight會直接變成BUHC 不管是duel人or queue
在custom mode裡的"hypixel head" 沒辦法吃 而且可以被放置出來
在Hitmlg 彈上去會馬上被拉下來且沒有傷害
edit: skywars pearl時會有傷害 還有不知道能不能在custom mode裡新增Pearl時會不會受到傷害

**Comment by lulu2002** [comment]
感謝回報！以下內容分別與 #38 #30 #9 重覆
最後的話，自定義模式中有選項可以調整 pearl 傷害唷！
