### ISSUE TITLE
/helpign spam

### ISSUE THREAD

**Issue by YukiSnowYue** [lulu2002/Naluwan-Issues#44]
![image](https://user-images.githubusercontent.com/73242379/122644612-a91c8080-d148-11eb-9f25-f1e73892f6db.png)
建議把指令改成server cooldown或延長冷卻 會有一群人濫用指令 ign也無法隱藏

**Comment by lulu2002** [comment]
感謝回報！

**Comment by lulu2002** [comment]
已解決，伺服器更新後便會套用 (一個人使用指令後，其他人至少要等待 30 秒後才可以使用指令)
![image](https://user-images.githubusercontent.com/41278925/122665357-4c1cdb00-d1d9-11eb-9293-d8328d1e48e7.png)
