### ISSUE TITLE
疊到天花板高度會TP的機制影響mlg模式&cave fight

### ISSUE THREAD

**Issue by YukiSnowYue** [lulu2002/Naluwan-Issues#45]
如題 在場地中疊太高把玩家TP回去的機制可以再優化
比如增加提示訊息等 這個機制也影響MLG的模式運作 被kb到天花板上就會直接傳送

另外cave fight現在似乎跟BUHC沒有差別 洞窟的地圖不見了

**Comment by lulu2002** [comment]
與 #30 #38  重覆，歡迎訂閱
