### ISSUE TITLE
新增聊天室過濾器指令(chatfilter)

### ISSUE THREAD

**Issue by YukiSnowYue** [lulu2002/Naluwan-Issues#46]
跟其他建議的/ign chat雷同 但自訂性更高
如果只是不希望特定字詞被看到(L noob等等) 就可以使用此功能
使用/chatfilter add (字詞)-過濾/隱藏指定字詞
使用/chatfilter remove-將特定字詞從隱藏列表中移除
使用/chatfilter list-顯示字詞隱藏/過濾列表

Ex.
/chatfilter add noob-把任何包含"noob"內容的訊息隱藏

**Comment by lulu2002** [comment]
感謝建議！能否請你稍微說明一下新增這功能的原因呢？目前那魯灣剛好在做大量系統更新，我希望可以設計出更符合玩家需求的產品。

**Comment by YukiSnowYue** [comment]
主要還是跟「玩家自訂性」有關
/ign chat&chatfilter並行的話 可以有效讓玩家「不只可以決定發言的對象 也可以在自己的遊玩體驗上進行言論審查」
當伺服器出現大量洗重複字詞的玩家,不論是假帳號或是真人
使用/ign chat的話 當人多起來是無法擋掉的
如果以「字詞」的角度去阻擋 只要輸入幾次就可以一勞永逸 

使用chatfilter的其他情境大概是
「我對這個字詞特別反感 但聊天室真的太多人使用了」
「我對於使用這個字詞的人沒有特別的意見 就單純不想要看到這個字而已」
或者當作ign chat的一部份功能進行優化也是可以的 畢竟這兩個機制都是以「自訂聊天室內容」為主 重複的地方也不少

其他對於ign功能的建議-能把ign功能給改成gui介面&/ign (玩家) (原因)
這可以提升不少方便性 使用起來也比較直觀
以現有的/ign ?來說
列表會貼在聊天室 容易被洗掉,同時每要解除ign一次 就要打一次指令
而列表也不會隨著自己新增/移除即時變動

改成gui介面介面的話
我一看到介面上的玩家頭顱(也可以補充上ign的日期) 這樣可以很直觀的確認
甚至只要對介面上的玩家頭顱點一下左鍵就可以將玩家移除ign列表
我覺得這麼做會讓ign功能變得更方便也比較簡單些
而將ign的指令改一些 變成/ign (玩家) (原因)
原因可以不必打 這樣可以比較方便做筆記.
