### ISSUE TITLE
地圖問題

### ISSUE THREAD

**Issue by YTRK** [lulu2002/Naluwan-Issues#50]
這兩天有幾張builduhc地圖好像都沒刷新  都有一攤一攤的水 放在地上哪種  還有整片都是水的那種
![Minecraft 1 8 9 110_6_21 上午 10_04_07](https://user-images.githubusercontent.com/86210881/122697701-770a3c00-d278-11eb-911e-c1e6e2d3173e.png)

**Comment by lulu2002** [comment]
與 #21 重覆，感謝回報
