### ISSUE TITLE
我想玩Castlewars😐😐😐

### ISSUE THREAD

**Issue by chchee3300** [lulu2002/Naluwan-Issues#52]
魯魯拜託啦🤑🤑🤑我想要玩castlewars😝😝跟李神拿插件讓玩家玩並搭配party系統啦😛罷拖啦🤚🤚嗚嗚😐😐😐我想玩遊戲🤪🤪🤪我不能玩遊戲了🤝🤝

**Comment by lulu2002** [comment]
好謝謝，壞示範

**Comment by lulu2002** [comment]
https://tinyurl.com/xzbb6zk

已新增！
