### ISSUE TITLE
更新後的幾個小bug

### ISSUE THREAD

**Issue by YukiSnowYue** [lulu2002/Naluwan-Issues#55]
1.PotPVP,Cave Fight(不知道是不是和BUHC共用同個排版)&Gapple模式的排版設定消失了 
2.新版ign系統沒有查看ign名單的功能 無法確認各個黑名單內的玩家

**Comment by lulu2002** [comment]
排版因為更新無法支援的關係，所以都清除了，這點實在不好意思。
至於 Ign 功能，是可以用 /ign list 查看的喔，只是不是很好用而已

如果想要知道 ign 的狀態，其實直接用 /ign <該玩家> 就可以打開 gui，看看 ign 了哪些

**Comment by lulu2002** [comment]
我曾經想過是否該支援離線的玩家，但後來覺得沒有需要。

如果有什麼想法歡迎再提出來，沒有的話就先關板了！

**Comment by YukiSnowYue** [comment]
原來如此 感謝:D
如果未來能改進ign list就好了
ign list對於經常檢查黑名單的玩家會有很大的需求 希望未來能改的更直觀
