### ISSUE TITLE
取消kda排行榜 

### ISSUE THREAD

**Issue by FBIJustGotMe** [lulu2002/Naluwan-Issues#61]
近來發現排行榜上的玩家多了幾個10000多%勝率 
查了一下 那幾位不外乎就是開小帳刷勝率 或著是使用外掛的玩家
現在排行榜似乎已經失去意義
如果把這東西拿掉說不定開外掛的玩家會減少一些 
畢竟動機沒了

**Comment by FBIJustGotMe** [comment]
加上排行榜上的玩家是外掛給人的觀感就不太好..

**Comment by lulu2002** [comment]
可以，確實「排行榜」這個東西也不太符合那魯灣的風格，之後回移除

**Comment by lulu2002** [comment]
已移除，重起後便會生效
