### ISSUE TITLE
BUG 有人會OBI自己然後跑到下層去

### ISSUE THREAD

**Issue by wKchanTW** [lulu2002/Naluwan-Issues#76]
![image](https://user-images.githubusercontent.com/85673250/123544342-6c263e80-d785-11eb-9ca0-bc2ffdbc87bd.png)
我是不會這個BUG拉所以我也不知道實際實行方法 反正就是有人會弄成這樣就要等20分鐘等他結束不然就退出

**Comment by lulu2002** [comment]
這個很難解決，為了修正此問題會導致地圖變得不好看，不過遇到這種玩家可以善用IGN 功能
