### ISSUE TITLE
伺服器偶爾會有lag問題

### ISSUE THREAD

**Issue by chchee3300** [lulu2002/Naluwan-Issues#78]
在打人的時候有機會會快速的double hit以及會有玩家速度突然變快或停住的問題

**Comment by lulu2002** [comment]
請問是哪種 Lag 呢？
這個問題的敘述比較不完整，還請提供詳細一點的資訊

**Comment by chchee3300** [comment]
在攻擊人的時候 有機率hit會delay 或是造成double hit的狀況
或是在攻擊時 敵人會停住 下一秒會瞬移到另一個地方 並在當下我對他攻擊是無效的
也就是lag spike
但詳細發生原因並不明 但相當多人都遇到這個問題 基本上全伺服器都這樣 包含在通話的所有人都會有此問題

**Comment by chchee3300** [comment]
當時的人數為30~40位 ping值穩定為30ping

**Comment by chchee3300** [comment]
https://youtu.be/tPaRXxPIqb4

**Comment by lulu2002** [comment]
已解決
