### ISSUE TITLE
會員可以辦活動

### ISSUE THREAD

**Issue by Kiruilo** [lulu2002/Naluwan-Issues#8]
希望可以讓會員可以辦活動 插件的(EVENTS)

**Comment by lulu2002** [comment]
感謝您的建議，能否請您針對 辦什麼樣的活動、功能有什麼，進行詳細一點的說明呢？感謝

**Comment by Kiruilo** [comment]
> 感謝您的建議，能​​否請您針對辦某種類型的活動，功能有什麼，進行詳細一點的說明呢？感謝
就是通常pvp伺服器會有一個辦活動的指令(events) 功能就是可以辦大型人加入這個活動 然後1v1淘汰賽

**Comment by Kiruilo** [comment]
> 感謝您的建議，能​​否請您針對辦某種類型的活動，功能有什麼，進行詳細一點的說明呢？感謝
就是通常pvp伺服器會有一個辦活動的指令(events) 功能就是可以辦大型人加入這個活動 然後1v1淘汰賽
