### ISSUE TITLE
long uhc

### ISSUE THREAD

**Issue by KryLaz** [lulu2002/Naluwan-Issues#94]
求求你了 longuhc改成普通16x16基岩墻的地圖 像syuu final uhc一樣 現在地圖這麽大 裝備這麽厚我全場只跑不打架也可以

**Comment by lulu2002** [comment]
我沒有辦法阻止每個人的風格，其實不只 long uhc，build uhc 要跑整場也是可以的。我倒是覺得這跟玩家本身的人格與玩法有關係，畢竟那魯灣只是一個 Practice Server，既然是練習的話，遇到這種人還是 ign 就好了

為了阻止這些玩家，而更改整個場地，犧牲掉那魯灣這麼多好看的風景我覺得是可惜了。

**Comment by KryLaz** [comment]
那long uhc不改 新增一個final uhc  16x16的地圖 同樣也要換裝備打架的模式 模擬真實uhc打到最後16x16 final fight的情況可以嗎

**Comment by lulu2002** [comment]
可以，麻煩您開一個全新的版面並敘述 FinalUHC 的模式內容，這個版面因為是為了討論拖時間的問題，所以就先到這裡。
