### ISSUE TITLE
新增final uhc模式

### ISSUE THREAD

**Issue by KryLaz** [lulu2002/Naluwan-Issues#95]
![2021-07-25_13 10 15](https://user-images.githubusercontent.com/87922386/126888460-2857702a-fbb0-4922-b170-26b2a081576f.png)
建議新增一個 finaluhc模式 讓玩家可以模擬真實uhc 傳送到最後16x16打架
裝備是一半耐久的prot 4鑽裝 以及替換的 full p3完整鑽裝 自定義模式好像有bug 調完裝備耐久不能按儲存
劍是s4 弓箭是p3
還有在自定義裏面找不到木頭 不知道是我眼殘還怎樣 方塊給予一組木頭 一組鵝卵石
地圖為16x16 平地

**Comment by lulu2002** [comment]
感謝建議！
