### ISSUE TITLE
不知最近怎麼的1.9+分支服已經都沒什麼人來玩了

### ISSUE THREAD

**Issue by newnamegaming** [lulu2002/Naluwan-Issues#97]
表面上看起來人數已經47人，但實際上在1.9+的只有一個人，主要是玩家分化太過嚴重且伺服器發展重心太過偏向1.8的原因，再加上PVP玩家停留在1.8的數量佔了絕對優勢，導致1.9+服涼涼。可否考慮一下有一定效果的曲線救服方式，就是進入1.9+的分支服毋須強制綁定Discord，放開一些內地玩家進入本服，因爲Discord在內地是要翻牆的。

**Comment by lulu2002** [comment]
謝謝您的意見，這是個好想法！，只可惜目前那魯灣還沒有這方面的打算，或許這個任務可以交給其他伺服器來～
